version: '2'

services:
  minecraft-server:
    image: itzg/minecraft-server
    container_name: minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - ./minecraft-data:/data
    environment:
      EULA: "TRUE"
      TYPE: "SPIGOT" #(SPIGOT|BUKKIT)
      VERSION: '1.11' #(SNAPSHOT|LATEST|V.ID)
      MOTD: 'Welcome to the UPGG Minecraft Server'
    tty: true
    stdin_open: true
    restart: always
